### ISSUE TITLE
Installing sdk 8.0.201 fails in macos.

### ISSUE THREAD

**Issue by DosangGu** [dotnet/install-scripts#440]
Used github actions [setup-dotnet](https://github.com/actions/setup-dotnet/tree/v4/) with following parameters.

```yml
      - uses: actions/setup-dotnet@v4
        continue-on-error: true
        with:
          dotnet-version: '8.x'
          dotnet-quality: 'ga'
```

And, got following errors below. Seems CDN is not prepared yet or broken.

```sh
/Users/someotherplace/actions-runner/_work/_actions/actions/setup-dotnet/v4/externals/install-dotnet.sh --skip-non-versioned-files --channel 8.0 --quality ga
dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.201/dotnet-sdk-8.0.201-osx-arm64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: The resource at aka.ms link 'https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.201/dotnet-sdk-8.0.201-osx-arm64.tar.gz' is not available.
dotnet_install: Error: Could not find `.NET Core SDK` with version = 8.0.201
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
```
