### ISSUE TITLE
Publishing to BAR/Maestro will no longer support tokens

### ISSUE THREAD

**Issue by premun** [dotnet/install-scripts#502]
I noticed that you're still using `$(MaestroAccessToken)` when publishing internal builds in https://github.com/dotnet/install-scripts/blob/b7b3f8f40181c8f43634106a94f4b064d0709b98/eng/validate-sdk.yml#L35.

This token is getting deprecated in favour of using a secretless auth via a service connection.
You will need to change how you do this or your internal builds will soon break.
The change is not complicated and goes as follows:

Where your pipeline has something like this:
```yaml
- script: eng\update-packagesource.cmd 
    -gitHubPat $(BotAccount-dotnet-maestro-bot-PAT)
    -barToken $(MaestroAccessToken)
    -packagesSource $(Build.SourcesDirectory)/build_stage_artifacts
  displayName: Update package source
```

it will need to change to something like this:

```yaml
- task: AzureCLI@2
  displayName: Update package source
  inputs:
    azureSubscription: "Darc: Maestro Production"
    scriptLocation: scriptPath
    scriptPath: eng\update-packagesource.ps1
    arguments: >
	    -gitHubPat $(BotAccount-dotnet-maestro-bot-PAT)
	    -packagesSource $(Build.SourcesDirectory)/build_stage_artifacts
```

The differences between the snippets above are:
-	AzureCLI@2 task is used
-	The “Darc: Maestro Production” service connection is used.
Your pipeline will need to be approved to use this connection (reach out to First Responders).
-	The `$(MaestroAccessToken)` secret is removed
